name: 🤖 SOMAS Project Request
description: Start a new autonomous development project with SOMAS
title: "[SOMAS] "
labels: ["somas:dev", "somas-project"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 SOMAS Autonomous Development Pipeline
        
        Submit your project idea and let SOMAS (Self-Sovereign Orchestrated Multi-Agent System) handle the development from concept to production-ready code.
        
        ### Multi-Agent AI Team
        
        Your project will be developed by a team of specialized AI agents:
        - **Requirements Analysis** (@copilot somas-requirements) - Extracts structured requirements
        - **Architecture Design** (@copilot somas-architect, Codex Architect) - Designs system architecture
        - **Implementation** (@copilot somas-implementer, Codex Coder) - Generates production code
        - **Testing** (@copilot somas-tester) - Creates comprehensive test suites
        - **Security Review** (@copilot somas-security) - Scans for vulnerabilities
        - **Validation** (Gemini Validator) - Independent quality verification
        - **Documentation** (@copilot somas-documenter) - Creates complete documentation
        
        ### The Pipeline Stages
        
        1. **🎯 Ideation** - Requirements extraction and initial planning
        2. **📋 Specification** - Detailed specification creation (Codex Specifier)
        3. **🔬 Simulation** - Monte Carlo task optimization (Codex Simulator)
        4. **🏗️ Architecture** - System design and component architecture
        5. **⚙️ Implementation** - Code generation with 80%+ test coverage
        6. **✅ Validation** - Quality, security, and performance validation
        7. **📝 Staging** - Final review and deployment preparation
        
        Once you submit this issue, SOMAS will automatically begin the autonomous development process.

  - type: textarea
    id: project_idea
    attributes:
      label: Project Idea
      description: Describe your project idea in detail. What problem does it solve? What are the key features?
      placeholder: |
        Example: Create a CLI tool that analyzes GitHub repositories for code quality metrics.
        
        Features:
        - Clone and analyze any public GitHub repository
        - Generate reports on code complexity, test coverage, and documentation
        - Export results to JSON, CSV, or Markdown
        - Support for multiple programming languages
    validations:
      required: true

  - type: dropdown
    id: project_type
    attributes:
      label: Project Type
      description: What type of project are you requesting?
      options:
        - API (REST/GraphQL service)
        - CLI (Command-line tool)
        - Library (Reusable package)
        - Web App (Frontend application)
        - Script (Automation/utility script)
        - Other
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Project Complexity
      description: Estimate the complexity of this project to help SOMAS optimize resource allocation
      options:
        - Simple (< 500 lines, single file)
        - Moderate (500-2000 lines, few files)
        - Complex (2000-5000 lines, multiple modules)
        - Large (5000+ lines, complex architecture)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How urgent is this project?
      options:
        - Low (Nice to have, no deadline)
        - Medium (Important, flexible timeline)
        - High (Important, time-sensitive)
        - Critical (Urgent, blocking other work)
      default: "Medium (Important, flexible timeline)"
    validations:
      required: true

  - type: input
    id: programming_language
    attributes:
      label: Preferred Programming Language (Optional)
      description: If you have a language preference, specify it here
      placeholder: "e.g., Python, JavaScript, Go, Rust"

  - type: textarea
    id: constraints
    attributes:
      label: Technical Constraints or Requirements (Optional)
      description: Any specific technologies, frameworks, or constraints to consider?
      placeholder: |
        Example:
        - Must use Python 3.10+
        - Should include Docker containerization
        - Must have comprehensive error handling
        - Should follow PEP 8 style guide

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context (Optional)
      description: Any other information that might be helpful
      placeholder: "Links to similar projects, documentation, or other relevant resources"

  - type: markdown
    attributes:
      value: |
        ---
        
        ## What happens next?

        1. **Submit** this issue (labels are applied automatically)
        2. SOMAS will create a feature branch and draft PR
        3. Watch as the autonomous pipeline progresses through stages:
           - 🎯 **Ideation** - @copilot somas-requirements extracts requirements
           - 📋 **Specification** - Codex Specifier creates detailed spec
           - 🔬 **Simulation** - Codex Simulator optimizes task execution
           - 🏗️ **Architecture** - @copilot somas-architect designs system
           - ⚙️ **Implementation** - @copilot somas-implementer generates code
           - ✅ **Validation** - Multiple agents review quality and security
           - 📝 **Staging** - @copilot somas-merger prepares for deployment
        4. You'll be notified (@scotlaclair) when human approval is needed
        5. Review and approve the generated code
        
        ### Interacting with Agents
        
        You can interact with specific agents by mentioning them in issue comments:
        
        ```markdown
        @copilot somas-requirements
        
        Please add a requirement for API rate limiting with 1000 requests/hour.
        ```
        
        Available agents: somas-requirements, somas-architect, somas-implementer, somas-tester, 
        somas-reviewer, somas-security, somas-optimizer, somas-documenter, somas-debugger, 
        somas-merger, somas-orchestrator, somas-advisor
        
        See `.github/agents/README.md` for complete documentation.
        
        **Note:** You can monitor progress in the automatically created PR.
