staging:
  id: "staging"
  order: 7
  objective: "Prepare deployment and manage merge process"
  
  inputs:
    - "validation_report.json (from validation)"
    - "all_implementation_artifacts"
    - "SPEC.md"
    - "ARCHITECTURE.md"
    - "execution_plan.yml"
    
  outputs:
    - artifact: "pull_request"
      description: "PR with all artifacts and comprehensive description"
    - artifact: "DEPLOYMENT.md"
      sections:
        - "Deployment Overview"
        - "Pre-deployment Checklist"
        - "Deployment Steps"
        - "Configuration Changes"
        - "Database Migrations"
        - "Rollback Procedure"
        - "Post-deployment Verification"
        - "Known Issues"
    - artifact: "RELEASE_NOTES.md"
      sections:
        - "New Features"
        - "Bug Fixes"
        - "Improvements"
        - "Breaking Changes"
        - "Dependencies"
    - artifact: "final_report.json"
      contents:
        - "pipeline_metrics"
        - "quality_metrics"
        - "stage_durations"
        - "success_indicators"
        
  agents:
    primary: "deployer"
    documenter: "documenter"
    advisor: "advisor"  # For deployment strategy recommendations
    
  environment_behavior:
    dev:
      auto_merge: true
      require_approval: false
      branch_patterns:
        - "somas/*"
        - "dev"
        - "develop"
      merge_strategy: "squash"
      actions:
        - "Create PR"
        - "Run final checks"
        - "Auto-merge if checks pass"
        - "Update issue status"
        - "Notify completion"
    
    prod:
      auto_merge: false
      require_approval: true
      branch_patterns:
        - "main"
        - "master"
        - "production"
      merge_strategy: "merge-commit"
      approval_required_from:
        - "@scotlaclair"
      actions:
        - "Create PR"
        - "Run final checks"
        - "Request human approval"
        - "Wait for approval"
        - "Merge after approval"
        - "Create release tag"
        - "Generate release notes"
        - "Notify completion"
  
  quality_gates:
    - "All validation checks passed"
    - "No merge conflicts"
    - "Deployment documentation complete"
    - "Release notes generated"
    - "Rollback procedure documented"
    - "Final metrics collected"
    
  human_gate_conditional:
    dev: false  # No human gate in dev
    prod: true  # Human gate in prod
    
  auto_merge_to_dev: true  # As per config
  timeout_hours: 24
  
  merge_conflict_resolution:
    auto_resolve:
      - "formatting_differences"
      - "whitespace_changes"
      - "non_overlapping_changes"
      - "import_additions"
      - "documentation_updates"
    require_manual:
      - "overlapping_logic_changes"
      - "api_contract_changes"
      - "schema_modifications"
      - "breaking_changes"
  
  notes: |
    The Staging stage prepares code for deployment and manages the merge.
    Behavior differs based on environment:
    - Dev: Fully autonomous with auto-merge
    - Prod: Requires human approval before merge
    
    The Deployer agent creates comprehensive deployment documentation,
    resolves merge conflicts when possible, and handles the merge process.
    
    In dev environment, this stage is fully autonomous.
    In prod environment, this is the ONLY stage requiring human intervention.
